language: c

matrix:
    include:
        - os: linux
        env:
            - MATRIX_EVAL="brew install cppcheck"
        
        - os: osx
        env:
            - MATRIX_EVAL="sudo apt-get install cppcheck"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
    - make
    - make check